### ISSUE TITLE
Disable addon based on a flag in Brocfile

### ISSUE THREAD

**Issue by sivakumar-kailasam** [stefanpenner/ember-browser-stats#4]
Would it make sense to have a flag in the Brocfile to toggle this addon from showing the stats even during development since not all developers in a team might be interested in these stats? This would also help in removing addon's assets from the production vendor.js file.

**Comment by jasonmit** [comment]
:+1: @stefanpenner I can take this up if you're down with the enhancement.

**Comment by stefanpenner** [comment]
@jasonmit I am down for this!

idea: Ideally it should just not include the code when disabled. (so its production safe)

**Comment by jasonmit** [comment]
Yup, PR incoming
